## 深度学习01
tensorflow实现神经网络，小练习

In [80]:
import tensorflow as tf
import numpy as np

In [96]:
#0~1正太分布
x_data = np.random.rand(100).astype(np.float32)

In [93]:
x_data[1:2]

array([0.5495131], dtype=float32)

In [83]:
y_data = x_data*0.1 + 0.3

### 创建神经网络结构

In [88]:
Weights = tf.Variable(tf.random_uniform([1], -1, 1))
biases = tf.Variable(tf.zeros([1]))

In [89]:
y = Weights*x_data + biases

In [90]:
loss = tf.reduce_mean(tf.square(y - y_data))

梯度优化器，alpha是学习率，步长

In [91]:
optimizer = tf.train.GradientDescentOptimizer(0.5)
train = optimizer.minimize(loss)

In [59]:
init = tf.global_variables_initializer()

### 激活神经网咯

In [68]:
sess = tf.Session()
sess.run(init)

In [67]:
for i in range(1,201):
    sess.run(train)
    
    if i % 20 == 0:
        print(i, sess.run(Weights), sess.run(biases))

20 [0.0999999] [0.30000007]
40 [0.0999999] [0.30000007]
60 [0.0999999] [0.30000007]
80 [0.0999999] [0.30000007]
100 [0.0999999] [0.30000007]
120 [0.0999999] [0.30000007]
140 [0.0999999] [0.30000007]
160 [0.0999999] [0.30000007]
180 [0.0999999] [0.30000007]
200 [0.0999999] [0.30000007]


### tf的框架不是很熟悉，下面是一些小练习

In [72]:
t1 = tf.square(2)
print(type(t1))

<class 'tensorflow.python.framework.ops.Tensor'>


##### 1.练习tf.session()的两种用法

In [104]:
# Build a graph.
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b

#方式1
# Launch the graph in a session.
sess = tf.Session()

# Evaluate the tensor `c`.
print(sess.run(c))

#方式2
with tf.Session() as sess:
    result = sess.run(c)
    print(result)

30.0
30.0


In [136]:
#返回服从正态分布的n个值
v1=tf.Variable(tf.random_normal(shape=[4,3],mean=0,stddev=1),name='v1')
v2=tf.Variable(tf.constant(123),name='v2') #常数
v3=tf.Variable(tf.ones([4,3]),name='v3') #全1

#方式1
sess = tf.Session()
init = tf.initialize_all_variables()
sess.run(init) #先初始化
print(sess.run(v1))

print('==========')
#方式2
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(v1))
    print(sess.run(v2))
    print(sess.run(v3))

[[-0.3539108   0.11981868 -1.4098587 ]
 [-1.2650666   1.1192477   0.135821  ]
 [-0.25941697 -0.27708125  0.45804536]
 [-0.31131345 -0.90213853  0.75700223]]
[[-0.19245903 -0.6280875   0.5139842 ]
 [ 0.90787965 -0.4532622   0.4412122 ]
 [ 0.8621351   1.2975181  -0.40375742]
 [-0.996079   -0.86339086  0.35558647]]
123
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### 2.变量的练习,
变量加法

In [116]:
state = tf.Variable(0, name='counter')
print(state.name)

counter_1:0


In [115]:
one = tf.constant(1)
print(type(one))

<class 'tensorflow.python.framework.ops.Tensor'>


In [119]:
new_value = tf.add(state, one)
#赋值，更新
update = tf.assign(state, new_value)

In [120]:
init = tf.global_variables_initializer()

In [122]:
with tf.Session() as sess:
    sess.run(init)
    
    for i in range(3):
        sess.run(update)
    print(sess.run(state))

3


#### 矩阵

In [131]:
matrix1 = tf.constant([[2,2]])
matrix2 = tf.constant([[3],
                       [3]])
result = tf.matmul(matrix1, matrix2)

with tf.Session() as sess:
    result = sess.run(result)
print(result)
print(matrix1.shape, matrix2.shape)

[[12]]
(1, 2) (2, 1)


#### 传入值

In [135]:
#输入值先hold
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)

output = tf.multiply(input1, input2)

with tf.Session() as sess:
    #feed_dict和placeholder绑定的
    print(sess.run(output, feed_dict={input1:[1.1],
                                    input2:[2.]}))

[2.2]
